# Generated by Django 4.2 on 2023-04-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beraterapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dateTime',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
