# Generated by Django 4.2 on 2023-04-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beraterapp', '0003_remove_user_username_remove_task_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('intensity', models.IntegerField()),
            ],
        ),
    ]
