# Generated by Django 4.2 on 2023-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beraterapp', '0004_insult'),
    ]

    operations = [
        migrations.AddField(
            model_name='insult',
            name='task_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
